name: 'beejanride'
version: '1.0.0'
config-version: 2

profile: 'beejanride'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  beejanride:
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]
    intermediate:
      +materialized: ephemeral
      +tags: ["intermediate"]
    marts:
      +materialized: table
      finance:
        +tags: ["finance"]
      drivers:
        +tags: ["operations"]
      riders:
        +tags: ["operations"]

snapshots:
  beejanride:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at
