version: 2

seeds:
  - name: trips_raw
    config:
      schema: beejanride_raw
      column_types:
        requested_at: timestamp
        pickup_at: timestamp
        dropoff_at: timestamp
        created_at: timestamp
        updated_at: timestamp

  - name: drivers_raw
    config:
      schema: beejanride_raw
      column_types:
        created_at: timestamp
        updated_at: timestamp

  - name: riders_raw
    config:
      schema: beejanride_raw
      column_types:
        created_at: timestamp

  - name: payments_raw
    config:
      schema: beejanride_raw
      column_types:
        created_at: timestamp

  - name: cities_raw
    config:
      schema: beejanride_raw

  - name: driver_status_events_raw
    config:
      schema: beejanride_raw
      column_types:
        event_timestamp: timestamp
